<?php
header('Content-type: text/html; charset=UTF-8'); 
require 'admin/PHPMailer/SMTP.php';
require 'admin/PHPMailer/PHPMailer.php';

$nome = $_POST['nome'];
$email = $_POST['email'];
$mensagem = $_POST['mensagem'];

/* Usando MailTrap */
$mail = new PHPMailer();

$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = 'f584d6584ddf8d'; //paste one generated by Mailtrap
$mail->Password = '4f91326e650604'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;


$mail->setFrom($email, $nome);
$mail->addAddress('teste@gmail.com', 'Teste'); 


$mail->Subject = 'Contato Grecia Burguer.';
$mail->isHTML(true);

$mailContent = '
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Grécia Burguer</title>
	<style>
		body,html,p, h2 {
			font-family: Arial
		}
	</style>
</head>
<body>
<div style="width: 700px; margin: 0 auto;">
	<table style="width: 100%">
		<thead>
			<tr>
				<th align="center" style="background-color: #ccc;">
	               <img src="assets/img/logo.png" alt="" width="250px;" align="center">
					
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<h2>Novo email do site</h2>
					<p>Nome: <strong>'.$nome.'</strong></p>
					<p>E-mail: <strong>'. $email .'</strong></p>
					<p>Mensagem: <strong>'. $mensagem .'</strong></p>
				</td>
			</tr>
		</tbody>
	</table>
</div>
</body>
</html>
';
$mail->Body = $mailContent;


if($mail->send()){
    $msg = 'Mensagem enviada';
	header("Location: index.php?msg=$msg");

}else{
    echo 'Erro ao enviar.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}

?>